version: '3.6'
services:
  setup:
    environment:
      - CONNECTION_STRING=AccountEndpoint=https://wemogysubscriptionscosmos.documents.azure.com:443/;AccountKey=LDCG7zzjNiVKztpuN6NugJYMFxMldfeMzpOJYWz41S5ulpsbxdtfiHhPDKoiyBp5G7KSgAAap5XifpF8rRwbeQ==;
    network_mode: host

  cosmosdb:
    environment:
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
