version: '3.6'
services:
  setup:
    build:
      context: ../../
      dockerfile: Dockerfile
    command:
      - "{\"databaseName\": \"subscriptions\", \"containers\": [{\"name\": \"addons\", \"partitionKey\": \"/partitionKey\"}, {\"name\": \"consumptions\", \"partitionKey\": \"/tenantId\"}, {\"name\": \"features\", \"partitionKey\": \"/partitionKey\"}, {\"name\": \"quotaunits\", \"partitionKey\": \"/partitionKey\"}, {\"name\": \"subscriptions\", \"partitionKey\": \"/partitionKey\"}, {\"name\": \"tenants\", \"partitionKey\": \"/partitionKey\"}]}"
    depends_on:
      - cosmosdb

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    hostname: cosmosdb
    container_name: cosmosdb
    mem_limit: 3g
    cpus: 2.0
    ports:
      - "8081:8081"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
