name: Release

on:
  workflow_dispatch:
    inputs:
      version:        
        description: "The version to release"
        default: "1.0.0"      
        required: true
    
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - run: |
          docker buildx build \
            --push \
            --tag robinmanuelthiel/cosmos-db-setup:${{ github.event.inputs.version }} \
            --tag robinmanuelthiel/cosmos-db-setup:latest \
            .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Version ${{ github.event.inputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  